version: '3'

services:
  rust_ocr:
    build: 
      context: .
      dockerfile: Dockerfile
    image: codebanesr/rust_ocr:latest
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/app/shared_data

volumes:
  shared_data: